
###############################################################################
# 1) USER SETTINGS - EDIT HERE
###############################################################################

# ---------------------------------------------------------------------------
# INPUT FILE
# ---------------------------------------------------------------------------
# This file is usually generated by the P2Y12 cost-preparation SQL script.
COST_FILE  <- "<QUARTERLY_NET_ANNUAL_TREATMENT_COST_EXCEL_FILE>"
COST_SHEET <- "<QUARTERLY_NET_ANNUAL_TREATMENT_COST_SHEET>"

# ---------------------------------------------------------------------------
# OUTPUT FILES
# ---------------------------------------------------------------------------
OUTPUT_PNG_FILE <- "<NET_ANNUAL_TREATMENT_COST_FIGURE_PNG_FILE>"
OUTPUT_SVG_FILE <- "<NET_ANNUAL_TREATMENT_COST_FIGURE_SVG_FILE>"

# ---------------------------------------------------------------------------
# COLUMN NAMES
# ---------------------------------------------------------------------------
DRUG_COL         <- "drug"
BRAND_GENERIC_COL <- "generic_brand"
YEAR_COL         <- "year"
QUARTER_COL      <- "quarter"
COST_COL         <- "net_annual_treatment_cost"

# ---------------------------------------------------------------------------
# DRUG SELECTION
# ---------------------------------------------------------------------------
SHOW_CLOPIDOGREL <- TRUE
SHOW_TICAGRELOR  <- TRUE
SHOW_PRASUGREL   <- TRUE

# ---------------------------------------------------------------------------
# SMOOTHING SETTINGS
# ---------------------------------------------------------------------------
# Smaller values produce smoother curves; larger values allow more flexibility.
GAM_K <- 6

# ---------------------------------------------------------------------------
# PLOT APPEARANCE
# ---------------------------------------------------------------------------
DRUG_COLORS <- c(
  "clopidogrel" = "#F09A4A",
  "prasugrel"   = "#355360",
  "ticagrelor"  = "#59BAED"
)

Y_AXIS_LIMITS <- c(0, 4000)
Y_AXIS_BREAKS <- seq(0, 4000, by = 1000)

YEAR_TICKS <- c(2011, 2012, 2014, 2016, 2018, 2020, 2022, 2024)

PLOT_WIDTH_IN  <- 7
PLOT_HEIGHT_IN <- 5
PLOT_DPI       <- 300


###############################################################################
# 2) LOAD PACKAGES
###############################################################################

required_packages <- c(
  "dplyr",
  "stringr",
  "readxl",
  "ggplot2",
  "mgcv",
  "grid",
  "svglite",
  "scales"
)

missing_packages <- required_packages[
  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)
]

if (length(missing_packages) > 0) {
  stop(
    "Please install the following R packages before running this script: ",
    paste(missing_packages, collapse = ", ")
  )
}

suppressPackageStartupMessages({
  library(dplyr)
  library(stringr)
  library(readxl)
  library(ggplot2)
  library(mgcv)
  library(grid)
  library(svglite)
  library(scales)
})


###############################################################################
# 3) HELPER FUNCTIONS
###############################################################################

normalize_drug <- function(x) {
  x <- stringr::str_to_lower(stringr::str_trim(as.character(x)))
  
  dplyr::case_when(
    x == "clopidogrel" ~ "clopidogrel",
    x == "prasugrel" ~ "prasugrel",
    x == "ticagrelor" ~ "ticagrelor",
    TRUE ~ x
  )
}

normalize_brand_generic <- function(x) {
  x <- stringr::str_to_lower(stringr::str_trim(as.character(x)))
  
  dplyr::case_when(
    x %in% c("brand", "brand-name", "brand name", "branded") ~ "Brand-name",
    x %in% c("generic", "generics") ~ "Generic",
    TRUE ~ as.character(x)
  )
}


###############################################################################
# 4) READ INPUT DATA
###############################################################################

cost_raw <- readxl::read_excel(
  COST_FILE,
  sheet = COST_SHEET
)

required_columns <- c(
  DRUG_COL,
  BRAND_GENERIC_COL,
  YEAR_COL,
  QUARTER_COL,
  COST_COL
)

missing_columns <- setdiff(required_columns, names(cost_raw))

if (length(missing_columns) > 0) {
  stop(
    "The cost file is missing required columns: ",
    paste(missing_columns, collapse = ", "),
    "\nAvailable columns are: ",
    paste(names(cost_raw), collapse = ", ")
  )
}


###############################################################################
# 5) PREPARE DATA
###############################################################################

show_drugs <- c(
  "clopidogrel" = SHOW_CLOPIDOGREL,
  "ticagrelor"  = SHOW_TICAGRELOR,
  "prasugrel"   = SHOW_PRASUGREL
)

selected_drugs <- names(show_drugs)[show_drugs]

if (length(selected_drugs) == 0) {
  stop("At least one drug must be selected for plotting.")
}

legend_levels <- c(
  "Brand-name clopidogrel",
  "Generic clopidogrel",
  "Brand-name prasugrel",
  "Generic prasugrel",
  "Brand-name ticagrelor"
)

cost_data <- cost_raw %>%
  transmute(
    drug = normalize_drug(.data[[DRUG_COL]]),
    brand_generic = normalize_brand_generic(.data[[BRAND_GENERIC_COL]]),
    year = as.integer(.data[[YEAR_COL]]),
    quarter = as.integer(.data[[QUARTER_COL]]),
    net_annual_treatment_cost = as.numeric(.data[[COST_COL]])
  ) %>%
  filter(
    drug %in% selected_drugs,
    quarter %in% c(1L, 2L, 3L, 4L),
    !is.na(year),
    !is.na(quarter),
    !is.na(net_annual_treatment_cost)
  ) %>%
  mutate(
    quarter_label = paste0(year, "-Q", quarter),
    legend_group = paste(brand_generic, drug)
  ) %>%
  arrange(year, quarter) %>%
  mutate(
    quarter_label = factor(
      quarter_label,
      levels = unique(quarter_label)
    ),
    quarter_index = as.integer(quarter_label),
    legend_group = factor(
      legend_group,
      levels = legend_levels
    )
  ) %>%
  filter(!is.na(legend_group))

if (nrow(cost_data) == 0) {
  stop("No rows remain after filtering to selected drugs and valid legend groups.")
}


###############################################################################
# 6) DEFINE COLORS, LINE TYPES, AND AXIS BREAKS
###############################################################################

drug_part <- stringr::str_extract(legend_levels, "[^ ]+$")
brand_part <- stringr::str_extract(legend_levels, "^[^ ]+")

color_map <- setNames(
  unname(DRUG_COLORS[drug_part]),
  legend_levels
)

linetype_map <- setNames(
  ifelse(brand_part == "Generic", "31", "solid"),
  legend_levels
)

year_breaks <- cost_data %>%
  distinct(year, quarter, quarter_index) %>%
  filter(
    quarter == 1L,
    year %in% YEAR_TICKS
  ) %>%
  arrange(year) %>%
  transmute(
    year,
    x_break = quarter_index
  )

n_quarters <- nlevels(cost_data$quarter_label)
x_axis_padding <- 0.38


###############################################################################
# 7) CREATE LEGEND DUMMY DATA
###############################################################################
# The invisible legend dummy ensures that active legend entries are displayed
# consistently, even when some smoothed curves have limited data.

legend_dummy <- tibble(
  quarter_index = rep(c(1, 2), times = length(legend_levels)),
  net_annual_treatment_cost = rep(
    Y_AXIS_LIMITS[1],
    times = 2 * length(legend_levels)
  ),
  legend_group = factor(
    rep(legend_levels, each = 2),
    levels = legend_levels
  )
)


###############################################################################
# 8) CREATE SMOOTHING LAYERS
###############################################################################
# Non-clopidogrel curves are drawn first.
# Clopidogrel curves are drawn afterward so they remain visible if lines overlap.

smooth_non_clopidogrel <- geom_smooth(
  data = cost_data %>%
    filter(!stringr::str_detect(as.character(legend_group), "clopidogrel")),
  aes(
    x = quarter_index,
    y = net_annual_treatment_cost,
    color = legend_group,
    linetype = legend_group,
    group = legend_group
  ),
  method = "gam",
  formula = y ~ s(x, bs = "cs", k = GAM_K),
  se = FALSE,
  linewidth = 1,
  na.rm = TRUE
)

smooth_clopidogrel <- geom_smooth(
  data = cost_data %>%
    filter(stringr::str_detect(as.character(legend_group), "clopidogrel")),
  aes(
    x = quarter_index,
    y = net_annual_treatment_cost,
    color = legend_group,
    linetype = legend_group,
    group = legend_group
  ),
  method = "gam",
  formula = y ~ s(x, bs = "cs", k = GAM_K),
  se = FALSE,
  linewidth = 1,
  na.rm = TRUE
)


###############################################################################
# 9) CREATE PLOT
###############################################################################

cost_plot <- ggplot() +
  
  geom_line(
    data = legend_dummy,
    aes(
      x = quarter_index,
      y = net_annual_treatment_cost,
      color = legend_group,
      linetype = legend_group,
      group = legend_group
    ),
    inherit.aes = FALSE,
    linewidth = 1,
    alpha = 0,
    show.legend = TRUE
  ) +
  
  smooth_non_clopidogrel +
  smooth_clopidogrel +
  
  scale_y_continuous(
    breaks = Y_AXIS_BREAKS,
    expand = expansion(mult = c(0, 0), add = c(0, 0))
  ) +
  
  scale_color_manual(
    values = color_map[legend_levels],
    breaks = legend_levels,
    drop = FALSE,
    name = NULL
  ) +
  
  scale_linetype_manual(
    values = linetype_map[legend_levels],
    breaks = legend_levels,
    drop = FALSE,
    name = NULL
  ) +
  
  scale_x_continuous(
    breaks = year_breaks$x_break,
    labels = year_breaks$year,
    expand = expansion(mult = c(0, 0), add = c(0, 0))
  ) +
  
  coord_cartesian(
    xlim = c(1 - x_axis_padding, n_quarters + x_axis_padding),
    ylim = Y_AXIS_LIMITS,
    clip = "off"
  ) +
  
  guides(
    color = guide_legend(
      override.aes = list(alpha = 1, linewidth = 1)
    ),
    linetype = guide_legend(
      override.aes = list(alpha = 1, linewidth = 1)
    )
  ) +
  
  theme_minimal(base_size = 12) +
  
  theme(
    plot.margin = margin(10, 20, 10, 10),
    
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_line(
      linewidth = 0.3,
      colour = scales::alpha("grey30", 0.3)
    ),
    panel.grid.minor.y = element_blank(),
    
    axis.line = element_line(linewidth = 0.3, colour = "black"),
    axis.ticks = element_line(linewidth = 0.3, colour = "black"),
    axis.ticks.length = grid::unit(4, "pt"),
    
    axis.text.x = element_text(size = 12, colour = "#000000"),
    axis.title.x = element_text(
      size = 12,
      colour = "#000000",
      margin = margin(t = 10)
    ),
    axis.text.y = element_text(size = 12, colour = "#000000"),
    axis.title.y = element_text(
      size = 12,
      colour = "#000000",
      margin = margin(r = 10)
    ),
    
    legend.position = c(0.98, 0.99),
    legend.justification = c(1, 1),
    legend.direction = "vertical",
    legend.box = "horizontal",
    legend.background = element_rect(
      fill = scales::alpha("white", 0.85),
      colour = scales::alpha("grey30", 0.3),
      linewidth = 0.2
    ),
    legend.margin = margin(6, 8, 6, 8),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    legend.key.height = grid::unit(0.45, "cm"),
    legend.key.width = grid::unit(0.70, "cm")
  ) +
  
  labs(
    y = "Net annual treatment cost",
    x = "Year"
  )

print(cost_plot)


###############################################################################
# 10) SAVE FIGURE
###############################################################################

ggsave(
  filename = OUTPUT_PNG_FILE,
  plot = cost_plot,
  width = PLOT_WIDTH_IN,
  height = PLOT_HEIGHT_IN,
  units = "in",
  dpi = PLOT_DPI
)

ggsave(
  filename = OUTPUT_SVG_FILE,
  plot = cost_plot,
  device = svglite::svglite,
  width = PLOT_WIDTH_IN,
  height = PLOT_HEIGHT_IN,
  units = "in"
)

message("Done. Net annual treatment-cost figure written to: ",
        OUTPUT_PNG_FILE, " and ", OUTPUT_SVG_FILE)